<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\AssureCloud.Application\AssureCloud.Application.csproj" />
    <ProjectReference Include="..\..\..\src\AssureCloud.Domain\AssureCloud.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\AssureCloud.Infrastructure\AssureCloud.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.7.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.7.2" />
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="FluentAssertions" Version="8.0.0" />
    <PackageReference Include="NetArchTest.Rules" Version="2.0.0" />
    <PackageReference Include="mediatR" Version="12.4.1" />
  </ItemGroup>

</Project>
